### ISSUE TITLE
Is there any difference of img file between Fly_Gemini_V1 & Fly_Gemini_V1.1?

### ISSUE THREAD

**Issue by gymdove** [Mellow-3D/Fly-Gemini-V1.1#1]
Hi
I get a  Fly_Gemini_V1.1 board from my friend. Try to make it work. When I burn the image of V1  into TF
the system reply:

![20230327224329](https://user-images.githubusercontent.com/4906883/227974900-e45231e1-a1fb-4f13-b822-9b49a1eefec8.jpg)

**Comment by jaysuk** [comment]
use the image from here https://mellow.klipper.cn/#/introduction/downloadimg
Thanks,

Jay

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
27/03/23,
15:47:50
